//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.20 at 06:33:27 PM IST 
//


package school;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="school_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="members" type="{http://www.school.com/schemas}Members"/>
 *         &lt;element name="board_members" type="{http://www.school.com/schemas}BoardMembers"/>
 *         &lt;element name="address" type="{http://www.school.com/schemas}Address"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "schoolName",
    "members",
    "boardMembers",
    "address"
})
@XmlRootElement(name = "school")
public class School {

    @XmlElement(name = "school_name", required = true)
    protected String schoolName;
    @XmlElement(required = true)
    protected Members members;
    @XmlElement(name = "board_members", required = true)
    protected BoardMembers boardMembers;
    @XmlElement(required = true)
    protected Address address;

    /**
     * Gets the value of the schoolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * Sets the value of the schoolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolName(String value) {
        this.schoolName = value;
    }

    /**
     * Gets the value of the members property.
     * 
     * @return
     *     possible object is
     *     {@link Members }
     *     
     */
    public Members getMembers() {
        return members;
    }

    /**
     * Sets the value of the members property.
     * 
     * @param value
     *     allowed object is
     *     {@link Members }
     *     
     */
    public void setMembers(Members value) {
        this.members = value;
    }

    /**
     * Gets the value of the boardMembers property.
     * 
     * @return
     *     possible object is
     *     {@link BoardMembers }
     *     
     */
    public BoardMembers getBoardMembers() {
        return boardMembers;
    }

    /**
     * Sets the value of the boardMembers property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoardMembers }
     *     
     */
    public void setBoardMembers(BoardMembers value) {
        this.boardMembers = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

}
